applications:
- api_domain: www.mailinator.com
  application_name: testapp
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: https://www.mailinator.com/
  type: web
deployment:
  environments:
  - dev
github_branch_protection:
  organization:
    amount_of_required_reviews: 2
    required_status_checks: []
plan_items:
  item-web-app-scanner:
    deployment:
      configuration:
      - testapp
      tags:
      - dev
      trigger: deployment
